#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0a8 on Mon Mar 22 09:42:54 2021
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 452))
        self.SetTitle("frame")

        self.panel_main = wx.Panel(self, wx.ID_ANY)

        sizer_main = wx.BoxSizer(wx.HORIZONTAL)

        sizer_main_left = wx.BoxSizer(wx.VERTICAL)
        sizer_main.Add(sizer_main_left, 1, wx.EXPAND, 0)

        self.grid_disp = wx.grid.Grid(self.panel_main, wx.ID_ANY, size=(1, 1))
        self.grid_disp.CreateGrid(10, 0)
        sizer_main_left.Add(self.grid_disp, 1, wx.ALL | wx.EXPAND, 5)

        self.button_read = wx.Button(self.panel_main, wx.ID_ANY, u"エクセル取込")
        self.button_read.SetMinSize((285, 50))
        sizer_main_left.Add(self.button_read, 0, wx.ALL | wx.EXPAND, 2)

        self.panel_right = wx.Panel(self.panel_main, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        sizer_main.Add(self.panel_right, 1, wx.ALL, 5)

        sizer_main_right = wx.GridBagSizer(0, 0)

        label_id = wx.StaticText(self.panel_right, wx.ID_ANY, u"ＩＤ")
        sizer_main_right.Add(label_id, (0, 0), (1, 1), wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 15)

        self.text_ctrl_id = wx.TextCtrl(self.panel_right, wx.ID_ANY, "")
        self.text_ctrl_id.SetMinSize((200, 23))
        sizer_main_right.Add(self.text_ctrl_id, (0, 1), (1, 1), wx.TOP, 10)

        label_pw = wx.StaticText(self.panel_right, wx.ID_ANY, u"ＰＷ")
        sizer_main_right.Add(label_pw, (1, 0), (1, 1), wx.LEFT | wx.TOP, 15)

        self.text_ctrl_pw = wx.TextCtrl(self.panel_right, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.text_ctrl_pw.SetMinSize((200, 23))
        sizer_main_right.Add(self.text_ctrl_pw, (1, 1), (1, 1), wx.TOP, 10)

        self.button_exec = wx.Button(self.panel_right, wx.ID_ANY, u"実行")
        self.button_exec.SetMinSize((260, 50))
        sizer_main_right.Add(self.button_exec, (2, 0), (1, 2), wx.ALL | wx.EXPAND, 10)

        self.panel_right.SetSizer(sizer_main_right)

        self.panel_main.SetSizer(sizer_main)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnRead, self.button_read)
        self.Bind(wx.EVT_BUTTON, self.OnExec, self.button_exec)
        # end wxGlade

    def OnRead(self, event):  # wxGlade: MainFrame.<event_handler>
        event.Skip()

    def OnExec(self, event):  # wxGlade: MainFrame.<event_handler>
        event.Skip()
